name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            whoami
            pwd

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/rankriot-crawler || (echo "Failed to change directory" && exit 1)
            git fetch origin || (echo "Failed to fetch" && exit 1)
            git reset --hard origin/main || (echo "Failed to reset" && exit 1)
            npm ci || (echo "Failed to install dependencies" && exit 1)
            npm run build || (echo "Failed to build" && exit 1)
            pm2 restart rankriot-crawler || pm2 start dist/server.js --name rankriot-crawler